Routing/Routing.Web/Controllers/ScenarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Routing.Domain.Dto.Command;
using System.Threading.Tasks;
using Routing.Domain.Dto.Abstracts;
using Routing.Domain.ReadModel;
using Routing.Web.Models.Scenario;

namespace Routing.Web.Controllers
{
    public class ScenarioController : Controller
    {
        References_ReadModel References_ReadModel;

        public ScenarioController(References_ReadModel _References_ReadModel)
        {
            References_ReadModel = _References_ReadModel;
        }
        //
        // GET : /Scenario/ 

        public ActionResult Index(int? page, int? pageSize)
        {
            var query = new Routing.Domain.Dto.Query.SearchScenarios 
            { 
                UserId = "users/1",
                PageIndex = page.GetValueOrDefault(1), 
                PageSize = pageSize.GetValueOrDefault(10)
            };

            var scenari = References_ReadModel.Search_Scenarios(query);
            var viewModel = new Search_Scenario_ViewModel { Scenari = scenari };
            return View(viewModel);
        }

        //public JsonResult Search(SearchDestinations query)
        //{
        //    var clients = DocumentSession.Query<Destination>()
        //        .To_DestinationDto()
        //        //.Apply_Sort_And_Paging(query, s => s.Id)
        //        .ToList();

        //    return Json(clients, JsonRequestBehavior.AllowGet);
        //}


        [HttpGet]
        public ActionResult Nuovo_Scenario()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Create_Scenario(Create_Scenario cmd)
        {
            return View();
        }


        //public Task<ViewResult> Index()
        //{
        //    return Task.Factory.StartNew(() => View());
        //}

    }
}

Routing/Routing.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <link href="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Content/css")" rel="stylesheet" type="text/css" />
        <link href="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Content/themes/base/css")" rel="stylesheet" type="text/css" />
        <script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Scripts/js")"></script>
        <meta name="viewport" content="width=device-width" />
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here.", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Scenari", "Index", "Scenario")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
                <div class="float-right">
                    <ul id="social">
                        <li><a href="http://facebook.com" class="facebook">Facebook</a></li>
                        <li><a href="http://twitter.com" class="twitter">Twitter</a></li>
                    </ul>
                </div>
            </div>
        </footer>
    </body>
</html>